version: '3'
services:
  bookhair:
    container_name: bookhair
    build:
      dockerfile: Dockerfile
    ports:
      - 3333:3000
  db:
    image: postgres:14.1-alpine
    volumes:
      - /pv/db:/var/lib/postgresql
    restart: always
    command: bash -c "docker exec -it db psql -U postgres -d mydb -a -f /mnt/c/Users/youne/OneDrive/Bureau/mydbbackup.sql"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Azerty-02
      - POSTGRES_DB=mydb
    ports:
      - '5432:5432'
