version: '3'
services:
  db:
    image: postgres:14.1-alpine
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Azerty-02
      - POSTGRES_DB=mydb
    ports:
      - '5432:5432'
  bookhair:
    depends_on:
      - db
    container_name: bookhair
    environment:
      DATABASE_URL: postgresql://postgres:Azerty-02@localhost:5432/mydb?schema=sample
    build:
      dockerfile: Dockerfile
    ports:
      - '3333:3000'
    volumes:
      - ./src:/app/src
