services:
  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      POSTGRES_PASSWORD: Azerty-02
      POSTGRES_DB: mydb
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  bookhair:
    container_name: bookhair
    build:
      context: ./bookhair
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
      - '5555:5555'
    volumes:
      - ./bookhair/src:/app/src